### ISSUE TITLE
In ros kinetic and gazebo 8, the gazebo is not subscribing the mobile_base/commands/velocity

### ISSUE THREAD

**Issue by onlytailei** [turtlebot/turtlebot_simulator#67] opened 2017-05-23 16:33 UTC
I installed gazebo8 and ros kinetic as the instructions from http://gazebosim.org/tutorials/?tut=ros_wrapper_versions#Gazebobuiltfromsource.

When I start the launch file in turltebot_gazebo.
It seemed that mobile_base/commands/velocity is not subscribed by gazebo node.
It never happens in gazebo 7/2 with ros indigo.
Then how can I control the robot in gazebo through ROS?

**Comment by onlytailei** [comment] 2017-05-23 16:34
The turlebot_simulator is compiled in workspace from source.

**Comment by tfoote** [comment] 2017-05-26 01:09
Can you please provide more specific details about how to reproduce your problem. What your workspace is and exactly the console outputs from your debugging that the node is not subscribing.

**Comment by onlytailei** [comment] 2017-05-26 08:42
Sorry, just find that I need to compile the kobuki also from the source as well.

**Comment by kivrakh** [comment] 2017-06-29 11:16
Hi,
I could not compile the kobuki from source because it gave a lot of errors since some functions are deprecated. That's why I couldn't move the turtlebot using turtlebot_teleop package. Have you accomplished to move turtlebot?

**Comment by onlytailei** [comment] 2017-06-29 12:39
@hassan82  I just compile it from source. Nothing is wrong.
Remember to compile all of the dependencies from source.

**Comment by kivrakh** [comment] 2017-07-01 13:33
Thanks @onlytailei for the help. I explain more about here to anyone who has this problem:
 
Install the **kobuki**, **kobuki_core**,  **kobuki_desktop**,  **kobuki_msgs** packages as _kinetic devel_ into your catkin workspace from:

[https://github.com/yujinrobot?language=&page=3&q=&type=&utf8=%E2%9C%93](url)

After that, run this command:

`rosdep install --from-paths src -i -y`

Finally, install **turtlebot**, **turtlebot_simulator** and  **gazebo_ros_pkgs** packages from:

https://github.com/turtlebot
https://github.com/ros-simulation/gazebo_ros_pkgs

Then `catkin_make`

**Comment by tfoote** [comment] 2017-09-18 07:27
Without more details such as debugging outputs, there's not enough information here to debug. I'm going to close this. If there's more details please comment back here and we can reopen.

**Closed as completed by tfoote** 2017-09-18 07:27 UTC
